server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/simulationdb
spring.datasource.username=postgres
spring.datasource.password=APDell2022
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none